name: Build
on: [push, pull_request]

jobs:
  PrereqChecker:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1.0.2
      with:
        nuget-version: 'latest'
    - name: Restore packages
      run: nuget restore PrereqChecker.sln
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Build with MSBuild
      run: msbuild PrereqChecker.sln
